import { DefaultPrivacyLevel, noop } from '@datadog/browser-core';
import { MutationCallBack } from './types';
/**
 * Buffers and aggregate mutations generated by a MutationObserver into MutationPayload
 */
export declare function startMutationObserver(controller: MutationController, mutationCallback: MutationCallBack, defaultPrivacyLevel: DefaultPrivacyLevel): {
    stop: typeof noop;
};
/**
 * Controls how mutations are processed, allowing to flush pending mutations.
 */
export declare class MutationController {
    private flushListener?;
    flush(): void;
    onFlush(listener: () => void): void;
}
export declare function sortAddedAndMovedNodes(nodes: Node[]): void;
